### ISSUE TITLE
python 3.12 not copatible with numba 0.58.1 

### ISSUE THREAD

**Issue by NCastro-Segura** [WD-planets/AstroToolkit#11]
Hi, I tried to install the package using pip in a fresh conda environment and got the following incompatibility with python 3.12: 

`Collecting astrotoolkit
  Using cached AstroToolkit-1.4.0-py3-none-any.whl.metadata (40 kB)
Collecting astropy==5.2.2 (from astrotoolkit)
  Using cached astropy-5.2.2.tar.gz (8.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting astroquery==0.4.7 (from astrotoolkit)
  Using cached astroquery-0.4.7-py3-none-any.whl.metadata (7.2 kB)
Collecting bokeh==3.1.1 (from astrotoolkit)
  Using cached bokeh-3.1.1-py3-none-any.whl.metadata (12 kB)
Collecting cmasher==1.6.3 (from astrotoolkit)
  Using cached cmasher-1.6.3-py3-none-any.whl.metadata (8.2 kB)
Collecting importlib-resources==6.4.0 (from astrotoolkit)
  Using cached importlib_resources-6.4.0-py3-none-any.whl.metadata (3.9 kB)
Collecting matplotlib==3.7.5 (from astrotoolkit)
  Using cached matplotlib-3.7.5-cp312-cp312-macosx_10_12_x86_64.whl.metadata (5.7 kB)
Collecting numba==0.58.1 (from astrotoolkit)
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qw/bm7knqg9493_9mh63wbjwdkh0000gp/T/pip-install-r1vvfzrx/numba_32b99bfef23941e398402134e322f357/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/qw/bm7knqg9493_9mh63wbjwdkh0000gp/T/pip-install-r1vvfzrx/numba_32b99bfef23941e398402134e322f357/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.2; only versions >=3.8,<3.12 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by EthanJMoorfield** [comment]
Hi, I have been looking into this, and it has revealed a much bigger issue. Essentially python 3.12+ would never work for the timeseries analysis tools. The original ones were not written by me, so I have taken these out for now and will hopefully make new ones soon that don't have so many dependencies to avoid further issues later on. The older versions of the toolkit can still be used on older python versions (<=3.11) for these features, but the new version (1.4.1) will work for python 3.12.

Thanks
