### ISSUE TITLE
Add module to retrieve ASAS-SN photometry

### ISSUE THREAD

**Issue by BGaensicke** [WD-planets/AstroToolkit#9]
This may not be straight-forward, as the interface to ASAS-SN doesn't seem to be designed for automated queries, https://asas-sn.osu.edu/photometry

I think Keith has experimented with ASAS-SN data, worth asking him.

**Comment by BGaensicke** [comment]
Just in case: ASAS-SN recently added a new service that allows direct queries of their data base, https://arxiv.org/abs/2304.03791

**Comment by EthanJMoorfield** [comment]
I'll have a look at this when I can, I think the webpage for the python implementation is down but if v2 gives a big enough advantage over v1, I can update it.

Thanks
